"""добавляю bpvtytybz

Revision ID: c3a4e5c563e2
Revises: f6461487f1d9
Create Date: 2023-04-23 18:39:23.106983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3a4e5c563e2'
down_revision = 'f6461487f1d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
