"""добавляю юзера

Revision ID: f6461487f1d9
Revises: a1e3a2d9be14
Create Date: 2023-04-23 18:29:32.127878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6461487f1d9'
down_revision = 'a1e3a2d9be14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('phone_number', sa.String(length=13), nullable=True),
    sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('parents_list', sa.Integer(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parents_list'], ['kazak.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('kazak', 'middle_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kazak', 'middle_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_table('user')
    # ### end Alembic commands ###
